version: "3.10"

services:
  itsoft_db:
    container_name: itsoft_db
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - my-datavolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  itsoft_api:
    container_name: itsoft_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - itsoft_db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}

  itsoft_front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "npm run dev"
    ports:
      - '8080:8080'
    depends_on:
      - itsoft_api

volumes:
  my-datavolume:
