# Generated by Django 5.0.1 on 2024-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limitOrder', '0002_rename_create_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PART_EXECUTED', 'PART_EXECUTED'), ('EXECUTED', 'EXECUTED')], default='PENDING', max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4),
        ),
    ]
